# 网站设置
title: A计划 - 足球数据分析
email: your-email@example.com
description: >- # 这意味着忽略换行符直到"baseurl:"
  A计划足球数据分析平台 - 专业的足球数据分析，提供精准的比赛分析和统计数据，助您洞察比赛背后的规律。
baseurl: "/jekyll_try" # 网站子路径，例如 /blog
url: "" # 网站的基础主机名和协议，例如 http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# 构建设置
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# 排除的文件和文件夹
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
